language: node_js
node_js:
  - "node"
  - "8"
before_install:
  - ls
install:
  - cd risServer
  - npm install
  - cd client
  - npm install
before_script:
  - ls
script:
  - ng build
        
   
notifications:
  email:
    - saku.rautiainen@iki.fi